name: flutter_widget_from_html
version: 0.3.2+2
description: Flutter plugin for widget tree building from html that supports hyperlink, image, nested list, etc.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  cached_network_image: ^2.0.0
  chewie: ^0.9.10
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.1
  flutter_widget_from_html_core:
    git:
      url: https://github.com/qeuyee/flutter_widget_from_html.git
      path: packages/core
  html: ^0.14.0+3
  url_launcher: ^5.4.2
  video_player: ^0.10.8+1
  webview_flutter:
    git:
      url: https://github.com/qeuyee/plugins.git
      ref: 2b14dea64a7272fa9828f5bfee564155443d6f89
      path: packages/webview_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
